version: '3'

services:
  djangoapp:
    restart: always
    build: ./app
    volumes:
      - ./app/src:/web/app/src
      - static_volume:/web/app/files/static  # <-- bind the static volume
      - media_volume:/web/app/files/media   # <-- bind the media volume
    env_file: 
      - ./env/dev.env
      - ./env/db.env
    networks:
      - nginx_network
      - database_network
    command: "/web/app/cmd.sh"

  nginx:
    restart: always 
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/web/app/files/static  # <-- bind the static volume
      - media_volume:/web/app/files/media  # <-- bind the media volume
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp
    networks:
      - nginx_network

  database:
    restart: always
    image: postgres:latest
    env_file: 
      - ./env/db.env
    volumes:
      - database_data:/var/lib/postgresql/data/
    networks:
      - database_network

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - redis_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  redis_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume 
  redis_data:  # <-- declare the redis volum
  database_data:  # <-- declare the database volume 

